[window]
decorations = "none"
padding = { x = 10, y = 10 }
opacity = 0.75

[colors.primary]
background = "#11111b"
foreground = "#cdd6f4"

[colors.cursor]
text = "#11111b"
cursor = "#cba6f7"

[colors.normal]
black   = "#1e1e2e"
red     = "#f38ba8"
green   = "#cba6f7"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#cba6f7"
cyan    = "#b4befe"
white   = "#cdd6f4"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#cba6f7"
yellow  = "#fab387"
blue    = "#89b4fa"
magenta = "#cba6f7"
cyan    = "#b4befe"
white   = "#a6adc8"

[colors.selection]
text = "#ffffff"
background = "#313244"

[colors.vi_mode_cursor]
text   = "#11111b"
cursor = "#cba6f7"
