[meta]
version = 1
name = "Omarchy"
description = "Follow your Omarchy system theme."
variant = "dark"
inherits = "vicinae-dark"
icon = "/home/atif/.local/share/omarchy/icon.png"

[colors.core]
background = "#1e1e2e"           # Surface 0
foreground = "#cdd6f4"           # Text
secondary_background = "#313244" # Surface 0
border = "#585b70"               # Surface 2
accent = "#cba6f7"               # Mauve accent

[colors.list.item.hover]
background = "#45475a"           # Surface 1
foreground = "#cdd6f4"

[colors.list.item.selection]
background = "#cba6f7"           # Mauve selection
foreground = "#1e1e2e"

[colors.accents]
blue = "#89b4fa"
green = "#cba6f7"
magenta = "#cba6f7"
orange = "#fab387"
purple = "#cba6f7"
red = "#f38ba8"
yellow = "#f9e2af"
cyan = "#b4befe"
